spring:
  application:
    name: lab3-embed
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: postgres
    password: Luudinhkien_2003
    url: jdbc:postgresql://localhost:5432/lab3
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        event:
          merge:
            entity_copy_observer: allow
